# Generated by Django 4.2 on 2023-05-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_user_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
